name: Deploy Practice Theme

on:
  push:
    branches:
      - main

jobs:
  deploy-theme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy theme via tar over SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST:       ${{ secrets.SSH_HOST }}
          SSH_PORT:       ${{ secrets.SSH_PORT }}
          SSH_USER:       ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -p $SSH_PORT -H $SSH_HOST >> ~/.ssh/known_hosts

          tar czf - -C wp-content/themes/practice-theme . \
            | ssh -i ~/.ssh/id_rsa -p $SSH_PORT $SSH_USER@$SSH_HOST \
                "mkdir -p domains/lightslategray-koala-907678.hostingersite.com/public_html/wp-content/themes/practice-theme && \
                 tar xzf - -C domains/lightslategray-koala-907678.hostingersite.com/public_html/wp-content/themes/practice-theme/"
